CREATE DATABASE [DESAFIOCARTSYS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DESAFIOCARTSYS', 
FILENAME = N'C:\TEMP\DESAFIOCARTSYS.mdf' , 
SIZE = 100 MB , FILEGROWTH = 1024KB )
 LOG ON ( NAME = N'DESAFIOCARTSY', 
FILENAME = N'C:\TEMP\DESAFIOCARTSY.ldf' , 
SIZE = 1024KB , FILEGROWTH = 10%)
GO

use desafiocartsys
CREATE TABLE CLIENTES
(
 ID uniqueidentifier CONSTRAINT Guid_Default DEFAULT NEWSEQUENTIALID() ROWGUIDCOL,
 NOME VARCHAR(200),
 DOCUMENTO VARCHAR(11),
 ESTADO_CIVIL INT,
 ATIVO INT
)


